version: '3.8'

# Development overrides for docker-compose.yml
services:
  backend:
    build:
      target: dev
    volumes:
      - ./packages/backend:/app/packages/backend
      - /app/packages/backend/node_modules
      - ./packages/shared:/app/packages/shared
      - /app/packages/shared/node_modules
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - DEBUG=*
      - ENABLE_CORS=true
    ports:
      - "3001:3001"
      - "9229:9229"  # Node.js debugging port
    stdin_open: true
    tty: true

  postgres:
    environment:
      - POSTGRES_DB=munchies_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./packages/database/init-dev.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes --loglevel debug

  # Development database management tool
  adminer:
    image: adminer:4.8.1
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
    depends_on:
      - postgres

  # Redis management tool
  redis-commander:
    image: rediscommander/redis-commander:latest
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis

volumes:
  postgres_dev_data:
  redis_dev_data:
